name: Release

on:
  push:
    paths:
      - pubspec.yaml
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: make install
      - run: make build.android

      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: release/${{ github.ref == 'refs/heads/main' && 'stable' || 'beta' }}
          FOLDER: ./build/app/outputs/apk/release
          CLEAN: true